#include "capsule.h"

#include "../physics_object.h"
#include <math.h>
#include "sphere.h"

// Generated by Copilot
void capsule_support_function(void* data, struct Vector3* direction, struct Vector3* output) {
    struct physics_object* object = (struct physics_object*)data;
    union physics_object_collision_shape_data* shape_data = &object->collision->shape_data;

    // Determine the point along the capsule's central axis that is furthest in `direction`
    float sign = (direction->y > 0.0f) ? 1.0f : -1.0f;
    struct Vector3 axis_point = { 0.0f, sign * shape_data->capsule.inner_half_height, 0.0f };

    // Offset by the capsule's radius in the direction of `direction`
    struct Vector3 radius_offset = {
        direction->x * shape_data->capsule.radius,
        direction->y * shape_data->capsule.radius,
        direction->z * shape_data->capsule.radius
    };

    // Combine the endpoint on the capsule's axis with the radius offset
    output->x = axis_point.x + radius_offset.x;
    output->y = axis_point.y + radius_offset.y;
    output->z = axis_point.z + radius_offset.z;
}


void capsule_bounding_box(void* data, struct Quaternion* rotation, struct AABB* box) {
    struct physics_object* object = (struct physics_object*)data;
    union physics_object_collision_shape_data* shape_data = &object->collision->shape_data;
    
    // Get capsule dimensions
    float half_height = shape_data->capsule.inner_half_height;
    float radius = shape_data->capsule.radius;

    // Define the capsule's central axis in local space
    struct Vector3 local_axis = { 0.0f, half_height, 0.0f };

    // Rotate the central axis by the given rotation to get its orientation in world space
    struct Vector3 world_axis;
    if(rotation)
        quatMultVector(rotation, &local_axis, &world_axis);
    else
        vector3Copy(&local_axis, &world_axis);

    // Calculate the extents by projecting the rotated axis and adding the radius
    float extent_x = fabsf(world_axis.x) + radius;
    float extent_y = fabsf(world_axis.y) + radius;
    float extent_z = fabsf(world_axis.z) + radius;

    // Set the AABB min and max based on the calculated extents
    box->min.x = -extent_x;
    box->min.y = -extent_y;
    box->min.z = -extent_z;

    box->max.x = extent_x;
    box->max.y = extent_y;
    box->max.z = extent_z;
}