#include "cylinder.h"

#include "../physics_object.h"
#include <math.h>

#define SQRT_1_2   0.707106781f

// Generated by Copilot
void cylinder_support_function(void* data, struct Vector3* direction, struct Vector3* output) {
    struct physics_object* object = (struct physics_object*)data;
    union physics_object_collision_shape_data* shape_data = &object->collision->shape_data;

    // Determine the point along the cylinder's central axis that is furthest in `direction`
    float sign = (direction->y > 0.0f) ? 1.0f : -1.0f;
    output->x = direction->x * shape_data->cylinder.radius;
    output->y = sign * shape_data->cylinder.half_height;
    output->z = direction->z * shape_data->cylinder.radius;

    // Normalize the x and z components to account for the radius
    float length = sqrtf(output->x * output->x + output->z * output->z);
    if (length > 0.0f) {
        output->x *= shape_data->cylinder.radius / length;
        output->z *= shape_data->cylinder.radius / length;
    }
}

void cylinder_bounding_box(void* data, struct Quaternion* rotation, struct AABB* box) {
    struct physics_object* object = (struct physics_object*)data;
    union physics_object_collision_shape_data* shape_data = &object->collision->shape_data;
    
    // Get cylinder dimensions
    float half_height = shape_data->cylinder.half_height;
    float radius = shape_data->cylinder.radius;

    // Define the cylinders's central axis in local space
    struct Vector3 local_axis = { 0.0f, half_height, 0.0f };

    // Rotate the central axis by the given rotation to get its orientation in world space
    struct Vector3 world_axis;
    if(rotation)
        quatMultVector(rotation, &local_axis, &world_axis);
    else
        vector3Copy(&local_axis, &world_axis);

    // Calculate the extents by projecting the rotated axis and adding the radius
    float extent_x = fabsf(world_axis.x) + radius;
    float extent_y = fabsf(world_axis.y);
    float extent_z = fabsf(world_axis.z) + radius;

    // Set the AABB min and max based on the calculated extents
    box->min.x = -extent_x;
    box->min.y = -extent_y;
    box->min.z = -extent_z;

    box->max.x = extent_x;
    box->max.y = extent_y;
    box->max.z = extent_z;
}